### ISSUE TITLE
Can we get pin saves, comments count and reactions too?

### ISSUE THREAD

**Issue by ahmednabik** [rit3zh/Pinterest.js#2]
The getPin returns lots of useful stats about a pin but could we also get number of saves, comments and reactions? Manually checking the page source indicates that these are present in the script tags from where other stats are scrapped.

**Comment by rit3zh** [comment]
Hey there!

Check out the latest version 14, there have been updates to the getPin function. Additionally, a new getComments function has been add as well.

**Comment by ahmednabik** [comment]
Thankyou. The new approach to get the pin resource data is very solid now. I spent several hours writing my own parser to get the missing items (saves, reactions, comments). should have waited for your reply lol.

Pin saves are still missing. you can access it via resource?.aggregated_pin_data?.aggregated_stats?.saves

If you include it, the data will be complete

**Comment by rit3zh** [comment]
In this new patch, I’ve laid the groundwork, but there’s still room for improvement. I’ll be releasing another patch, likely tomorrow, to make the structure more organized and polished.

**Comment by ahmednabik** [comment]
Great. Looking forward to it. Have you written any documentation?

**Comment by rit3zh** [comment]
I haven’t yet, but I’ll look forward for the documentation soon.
